### ISSUE TITLE
Local builds missing pictures and svg's

### ISSUE THREAD

**Issue by LFGaming** [berty/www.wesh.network#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Browser

Edge

### Browser version

Version 114.0.1823.67

### OS

Windows

### OS version

Windows 11 Home

### Device

ASUS Vivobook

### Steps to reproduce

1. Clone this repository.
2. Run `npm run dev` (do `npm install` first if needed)
3. Take a look at the local home page and then the home image and two images on the bottom will be gone.

### Current behavior

Here you can see what images will be gone. For me this happens on my Windows 10, Windows 11 (both using wsl) and Ubuntu machines.

<img width="933" alt="msedge_216GURB76f" src="https://github.com/berty/www.wesh.network/assets/38732192/e187540b-2428-438b-9897-67b0dbe930b1">
<img width="933" alt="msedge_57lOdVTg9l" src="https://github.com/berty/www.wesh.network/assets/38732192/19a19911-46c9-496d-86c8-cc883d7d2851">

### Expected behavior

I would guess the images would not be gone.

**Comment by LFGaming** [comment]
I also have a fix for this if this is reproduced by more people

**Comment by jefft0** [comment]
I ran `npm run dev` and it looks good to me.

![Screenshot 2023-07-06 at 16 01 27](https://github.com/berty/www.wesh.network/assets/1999543/49614e3b-f92f-404d-a1e6-d620be92b40c)

**Comment by jefft0** [comment]
I'm on macOS. Node.js version v16.16.0 . I haven't checked Windows or Ubuntu.

**Comment by LFGaming** [comment]
Hi @jefft0 for me problem was that for example the com file is called `COM.png` but in the code is `./img/Com.png`. When I change it to `./img/COM.png`, it works correctly.

**Comment by jefft0** [comment]
It looks like there was one commit which introduced a lot of these problems:
https://github.com/berty/www.wesh.network/commit/85f841109d94a98d2f71786fa770805bb073c24a

**Comment by LFGaming** [comment]
@jefft0 is it a good idea to push my pr with the changed image sources?

**Comment by jefft0** [comment]
Yes, I think this is a reasonable change. Please make a PR.

**Comment by LFGaming** [comment]
for me it is fixed with my pr so i will close this issue since it is merged.
