### ISSUE TITLE
Implement RSS support for the blog

### ISSUE THREAD

**Issue by kuchta** [berty/www.wesh.network#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Browser

Any browser

### Feature request

Please add rss support so people can follow you...

### Context

So that I know what's up.

**Comment by costinberty** [comment]
Hi! thanks for writing us. For the moment we are in the process of consolidating the technical foundations of Wesh Network protocol and Berty Messenger app. Once this is done we will revamp our communication channels, including the blog. At that point we will also take into account your suggestion of adding RSS. Please stay tunned :) until then we are closing this issue.
